// CNC v.js
const VALID_DUPL_LIST = [
'["ALL_SOURCE_ARTIFACTS_ARE_NOT_LOADING"]',
'["ALL_TARGET_ARTIFACTS_ARE_NOT_LOADING"]',
'["ALL_SOURCE_ARTIFACTS_ARE_NOT_LOADING","ALL_TARGET_ARTIFACTS_ARE_NOT_LOADING"]',
'["SOURCE_BRAND_HAS_NO_BRAND_INFO"]',
'["TARGET_BRAND_HAS_NO_BRAND_INFO"]',
'["SOURCE_BRAND_HAS_NO_BRAND_INFO","TARGET_BRAND_HAS_NO_BRAND_INFO"]',
'["SOURCE_IS_MIXED_UP_AND_TRUTH_SET_NOT_APPLICABLE"]',
'["TARGET_IS_MIXED_UP_AND_TRUTH_SET_NOT_APPLICABLE"]',
'["SOURCE_IS_MIXED_UP_AND_TRUTH_SET_NOT_APPLICABLE","TARGET_IS_MIXED_UP_AND_TRUTH_SET_NOT_APPLICABLE"]',
'["SOURCE_BRAND_TRADEMARK_IS_INCONCLUSIVE"]',
'["TARGET_BRAND_TRADEMARK_IS_INCONCLUSIVE"]',
'["SOURCE_BRAND_TRADEMARK_IS_INCONCLUSIVE","TARGET_BRAND_TRADEMARK_IS_INCONCLUSIVE"]'



];
