// UNQ.js
const VALID_UNQ_LIST = [
    '["COMPLETELY_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE","COMPLETELY_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["COMPLETELY_DIFFERENT_AND_SOURCE_HAS_MIXED_UP_ARTIFACTS","COMPLETELY_DIFFERENT_AND_TARGET_HAS_MIXED_UP_ARTIFACTS"]',
    '["COMPLETELY_DIFFERENT_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE","COMPLETELY_DIFFERENT_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["COMPLETELY_DIFFERENT_AND_SOURCE_HAS_MIXED_UP_ARTIFACTS"]',
    '["COMPLETELY_DIFFERENT_AND_TARGET_HAS_MIXED_UP_ARTIFACTS"]',
    '["COMPLETELY_DIFFERENT_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE"]',
    '["COMPLETELY_DIFFERENT_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["COMPLETELY_DIFFERENT"]',
    '["HOMONYMS_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE","HOMONYMS_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["HOMONYMS_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE"]',
    '["HOMONYMS_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["HOMONYMS"]',
    '["RELATED_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE","RELATED_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["RELATED_BASED_ON_TRUTH_SET_WITH_MIXED_UP_SOURCE"]',
    '["RELATED_BASED_ON_TRUTH_SET_WITH_MIXED_UP_TARGET"]',
    '["RELATED_BRANDS"]',
    '["TARGET_IS_MIXED_UP_AND_TRUTH_SET_NOT_APPLICABLE"]'
];